name: rsm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  provider: ^6.0.5
  flutter_localization: ^0.1.10
  get_it: ^7.2.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/josefinsans/josefinSans-Light.ttf
        - asset: assets/fonts/josefinsans/josefinSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/josefinsans/josefinSans-Regular.ttf
        - asset: assets/fonts/josefinsans/josefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/josefinsans/josefinSans-Bold.ttf
          weight: 700

